#!/usr/bin/env bash
#Configures system to resolve localhost to 127.0.0.2 and facebook.com to 8.8.8.8.

HOSTS_FILE="/etc/hosts"
cp "$HOSTS_FILE" "${HOSTS_FILE}.bak"

sed -i '/[[:space:]]localhost$/d' "$HOSTS_FILE"
sed -i '/facebook\.com/d' "$HOSTS_FILE"

echo "127.0.0.2 localhost" >> "$HOSTS_FILE"
echo "8.8.8.8 facebook.com" >> "$HOSTS_FILE"
