#!/usr/bin/env bash
#Configures system to resolve localhost to 127.0.0.2 and facebook.com to 8.8.8.8.

if [ "$(id -u)" -ne 0 ]; then
  echo "This script must be run as root"
  exit 1
fi

cp /etc/hosts /etc/hosts.bak

sed -i '/localhost/d' /etc/hosts
sed -i '/facebook.com/d' /etc/hosts

{
  echo "127.0.0.2 localhost"
  echo "8.8.8.8 facebook.com"
} >> /etc/hosts
