#!/usr/bin/env bash
# Configures system to resolve localhost to 127.0.0.2 and facebook.com to 8.8.8.8.

sudo sed -i '/localhost/d' /etc/hosts
sudo -i '/facebook.com/d' /etc/hosts


echo "127.0.0.2 localhost" |sudo tee -a /etc/hosts
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts
